### ISSUE TITLE
Please re-push the repo with proper authorship

### ISSUE THREAD

**Issue by im030** [orz811017/boost_bandwidth_via_speedtest#1]
As title, I believe most of your source code is "copied" from the repository below.
https://github.com/sivel/speedtest-cli

**Comment by orz811017** [comment]
> As title, I believe most of your source code is "copied" from the repository below.
> https://github.com/sivel/speedtest-cli
sorry I didn't know how to branch out a repo from the other repo before. I have forked a new repo from author sivel and I will close this repo later

**Comment by im030** [comment]
It's actually simple, you don't even have to close/remove current repository.

Just clone the original repo., add this repo. as additional remote(git remote add),
make your modification, force-push and it's done

**Comment by orz811017** [comment]
> It's actually simple, you don't even have to close/remove current repository.
> 
> Just clone the original repo., add this repo. as additional remote(git remote add),
> make your modification, force-push and

**Comment by orz811017** [comment]
Accident touch

**Comment by orz811017** [comment]
I will try it later. Thanks a lot

**Comment by orz811017** [comment]
it seems to be ok? 
If anything is still wrong, please let me know@@

**Comment by im030** [comment]
Yeah you did it right, I'm now closing this issue ;)
