### ISSUE TITLE
It's not executed repeatly

### ISSUE THREAD

**Issue by giveanornot** [orz811017/boost_bandwidth_via_speedtest#3]
After pulling the latest source code and installing it, the program is not executed repeatly.
Is it correct? I thought it should being keep executed in background.

![Screenshot_2021-04-11-14-59-33-260_com.termux.png](https://user-images.githubusercontent.com/54917072/114295371-6ea6bf80-9ad7-11eb-99f8-f5362e8522f5.png)

Thanks.

**Comment by orz811017** [comment]
I remove some codes since I only focus on windows environment before. very sorry for that and I revert some code for loop

**Comment by orz811017** [comment]
done
