### ISSUE TITLE
錯誤

### ISSUE THREAD

**Issue by MbaoWang** [orz811017/boost_bandwidth_via_speedtest#5]
Traceback (most recent call last):
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1491, in get_best_server
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bin/speedtest", line 33, in <module>
    sys.exit(load_entry_point('speedtest-cli==2.1.2', 'console_scripts', 'speedtest')())
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1884, in main
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1869, in shell
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1493, in get_best_server
speedtest.SpeedtestBestServerFailure: Unable to connect to servers to test latency.

以上使用merlin操作會發生此情況
使用exe有時候也會跳出錯誤訊息

**Comment by orz811017** [comment]
exe也是跳出相同的error嗎? 我只有看failed to execute the script....

至於這個error可以幫我把DEBUG設成TRUE看下其他log嗎?

**Comment by MbaoWang** [comment]
exe 是failed to execute the script沒錯
錯誤是不定時會發現
我放著看甚麼時候跳出來
感謝

**Comment by MbaoWang** [comment]
Retrieving speedtest.net configuration...
DEBUG: Timeout set to 10
DEBUG: User-Agent: Mozilla/5.0 (Linux-4.1.27-aarch64-with-glibc2.27; U; 64bit; en-us) Python/3.9.2 (KHTML, like Gecko) speedtest-cli/2.1.2
DEBUG: GET http://www.speedtest.net/speedtest-config.php?x=1618810205900.0
DEBUG: Redirected to https://www.speedtest.net/speedtest-config.php?x=1618810205900.0
DEBUG: Config XML:
b'<?xml version="1.0" encoding="UTF-8"?>\n<settings>\n<client ip="" lat="24.9389" lon="121.5422" isp="FarEasTone" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="TW" />\n<server-config threadcount="4" ignoreids="" notonmap="" forcepingid="" preferredserverid=""/>\n<licensekey>f7a45ced624d3a70-1df5b7cd427370f7-b91ee21d6cb22d7b</licensekey>\n<customer>speedtest</customer>\n<odometer start="19601573884" rate="12"/>\n<times dl1="5000000" dl2="35000000" dl3="800000000" ul1="1000000" ul2="8000000" ul3="35000000"/>\n<download testlength="10" initialtest="250K" mintestsize="250K" threadsperurl="4"/>\n<upload testlength="10" ratio="5" initialtest="0" mintestsize="32K" threads="2" maxchunksize="512K" maxchunkcount="50" threadsperurl="4"/>\n<latency testlength="10" waittime="50" timeout="20"/>\n<socket-download testlength="15" initialthreads="4" minthreads="4" maxthreads="32" threadratio="750K" maxsamplesize="5000000" minsamplesize="32000" startsamplesize="1000000" startbuffersize="1" bufferlength="5000" packetlength="1000" readbuffer="65536"/>\n<socket-upload testlength="15" initialthreads="dyn:tcpulthreads" minthreads="dyn:tcpulthreads" maxthreads="32" threadratio="750K" maxsamplesize="1000000" minsamplesize="32000" startsamplesize="100000" startbuffersize="2" bufferlength="1000" packetlength="1000" disabled="false"/>\n<socket-latency testlength="10" waittime="50" timeout="20"/>\n<translation lang="xml">\n</translation>\n\n</settings>'
DEBUG: Config:
{'client': {'ip': , 'lat': '24.9389', 'lon': '121.5422', 'isp': 'FarEasTone', 'isprating': '3.7', 'rating': '0', 'ispdlavg': '0', 'ispulavg': '0', 'loggedin': '0', 'country': 'TW'}, 'ignore_servers': [], 'sizes': {'upload': [524288, 1048576, 7340032], 'download': [350, 500, 750, 1000, 1500, 2000, 2500, 3000, 3500, 4000]}, 'counts': {'upload': 17, 'download': 4}, 'threads': {'upload': 2, 'download': 8}, 'length': {'upload': 10, 'download': 10}, 'upload_max': 51}
Testing from FarEasTone ()...
Retrieving speedtest.net server list...
DEBUG: GET http://www.speedtest.net/speedtest-servers-static.php?threads=8&x=1618810206363.0
DEBUG: GET http://c.speedtest.net/speedtest-servers-static.php?threads=8&x=1618810206771.0
DEBUG: GET http://www.speedtest.net/speedtest-servers.php?threads=8&x=1618810206920.0
DEBUG: GET http://c.speedtest.net/speedtest-servers.php?threads=8&x=1618810207614.0
Selecting best server based on ping...
DEBUG: GET http://www.speedtest.net/speedtest-servers-static.php?threads=8&x=1618810207733.0
DEBUG: GET http://c.speedtest.net/speedtest-servers-static.php?threads=8&x=1618810208154.0
DEBUG: GET http://www.speedtest.net/speedtest-servers.php?threads=8&x=1618810208274.0
DEBUG: GET http://c.speedtest.net/speedtest-servers.php?threads=8&x=1618810208954.0
DEBUG: Closest Servers:
[]
DEBUG: User-Agent: Mozilla/5.0 (Linux-4.1.27-aarch64-with-glibc2.27; U; 64bit; en-us) Python/3.9.2 (KHTML, like Gecko) speedtest-cli/2.1.2
Traceback (most recent call last):
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1491, in get_best_server
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bin/speedtest-cli", line 33, in <module>
    sys.exit(load_entry_point('speedtest-cli==2.1.2', 'console_scripts', 'speedtest-cli')())
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1884, in main
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1869, in shell
  File "/opt/lib/python3.9/site-packages/speedtest_cli-2.1.2-py3.9.egg/speedtest.py", line 1493, in get_best_server
speedtest.SpeedtestBestServerFailure: Unable to connect to servers to test latency.

以上是錯誤內容
謝謝

**Comment by orz811017** [comment]
周末有複現到這個issue 有更新過了 再麻煩看下

**Comment by MbaoWang** [comment]
HI 昨天更新過後結果連執行都不行了

Traceback (most recent call last):
  File "/opt/bin/speedtest-cli", line 33, in <module>
    sys.exit(load_entry_point('speedtest-cli==2.1.2', 'console_scripts', 'speedtest-cli')())
  File "/opt/bin/speedtest-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/lib/python3.9/importlib/metadata.py", line 79, in load
AttributeError: module 'speedtest' has no attribute 'main'

**Comment by orz811017** [comment]
呃 應該要可以吧 我是可以的欸...
![image](https://user-images.githubusercontent.com/19238768/115426409-0bcdca80-a233-11eb-831d-bfe35f4e0e5e.png)

**Comment by MbaoWang** [comment]
所以才覺得奇怪@@
![11111](https://user-images.githubusercontent.com/68382644/115432641-33279600-a239-11eb-9ca0-d45b6b748d47.png)
以上是安裝過程

**Comment by orz811017** [comment]
我把main加回去了 因為我平常不是這樣跑 不知道會有問題

**Comment by orz811017** [comment]
您pull下最新的應該就沒有問題了

**Comment by MbaoWang** [comment]
現在正常了，不過會變成間隔沒有秒數一直測

**Comment by orz811017** [comment]
之前實驗把Interval縮短了 剛剛沒注意到一起merge了抱歉抱歉

**Comment by MbaoWang** [comment]
沒關係 我知道怎麼改 感謝!! 我就close掉這個問題了
