### ISSUE TITLE
好像壞了

### ISSUE THREAD

**Issue by Bochan8778** [orz811017/boost_bandwidth_via_speedtest#6]
![71969F20-FB73-4EAD-82EB-0F2755C85786](https://user-images.githubusercontent.com/111365729/184894621-192df6eb-3694-4e54-92e8-ace5599fb240.jpeg)
![CAB2A372-BB7B-4C4B-A16E-054AF53A00D3](https://user-images.githubusercontent.com/111365729/184894643-68b7d5a0-9f5c-4254-9744-e824cb8e7234.jpeg)
如圖 好像不能用了

**Comment by azreal0515** [comment]
I try a min ago ,it's work!

**Comment by Bochan8778** [comment]
可以了 
我重裝兩次後就好了
